name: Test GitHub Schedule

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test Schedule
        run: |
          echo "SCHEDULE BERJALAN"
          echo "UTC:"
          date -u
          echo "WITA:"
          TZ=Asia/Makassar date
